import { Geist, Geist_Mono, Pattaya } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pattaya = Pattaya({
  variable: "--font-pattaya",
  subsets: ["latin"],
  weight: "400", // Use only the available weight
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pattaya.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
